<?php

class model_showcart3 extends model
{

    function __construct()
    {
        parent::__construct();
//
//        session_start();
//        $check = Model::sessionGet2('userId');
//        if ($check != true) {
//            header('location:'.URL.'showcart1/');
//        }
    }

    function index()
    {

    }

    function getBasketReViwe()
    {
        return parent::getBasket(); // TODO: Change the autogenerated stub
    }

    function postType()
    {



    }
}